# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /software/unreal5.11
GAMEPROJECTFILE =/home/natalie/Repos/Unreal/BlazingMoon/BlazingMoon.uproject

TARGETS = \
	BlazingMoon-Linux-DebugGame  \
	BlazingMoon-Linux-Shipping  \
	BlazingMoon \
	BlazingMoonEditor-Linux-DebugGame  \
	BlazingMoonEditor-Linux-Shipping  \
	BlazingMoonEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend BlazingMoonEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug BlazingMoonEditor-Linux-Debug


BlazingMoon-Linux-DebugGame:
	 $(PROJECTBUILD) BlazingMoon Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

BlazingMoon-Linux-Shipping:
	 $(PROJECTBUILD) BlazingMoon Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

BlazingMoon:
	 $(PROJECTBUILD) BlazingMoon Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

BlazingMoonEditor-Linux-DebugGame:
	 $(PROJECTBUILD) BlazingMoonEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

BlazingMoonEditor-Linux-Shipping:
	 $(PROJECTBUILD) BlazingMoonEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

BlazingMoonEditor:
	 $(PROJECTBUILD) BlazingMoonEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
